SELECT 
	FT.ID,
	FT.IDTaskDefinition, 
	DBO.CheckCampaign(IDTaskDefinition),
	DBO.Translate('PL-PL',CA.IDName),
	CA.ID,
	CA.IDAnswerType,
	FC.ContactDate 
FROM FO_TASK FT
INNER JOIN FO_ISSUE FI
ON FT.ID = FI.IDTask
INNER JOIN FO_ISSUE_CHANGE FIC
ON FI.ID = FIC.IDIssue
INNER JOIN FO_CONTACT FC
ON FC.ID = FIC.IDContact
INNER JOIN COM_ANSWER CA
ON CA.ID = COALESCE(FIC.IDAnswer4,FIC.IDAnswer3,FIC.IDAnswer2,FIC.IDAnswer1)
WHERE FT.ID IN (140114171)
--414622365
--417809914
--418613645)
ORDER BY FC.ContactDate DESC

