DECLARE	@vDate datetime = '2017-04-24 03:07:12'
--DECLARE @vSpid varchar(10) = '62'

DECLARE @tDeadlock TABLE
(
	DeadlockID BIGINT
)


INSERT INTO @tDeadlock (DeadlockID)
SELECT	EV.DeadlockID
FROM	dbo.EV_DEADLOCK EV WITH(NOLOCK)
WHERE	EV.RaportTimestampLocal BETWEEN DATEADD(minute, -1, ISNULL(@vDate, '1900-01-01')) AND DATEADD(minute, 1, ISNULL(@vDate,GETDATE())) 		


SELECT	'DEADLOCK'
SELECT	* 
FROM	dbo.EV_DEADLOCK EV WITH(NOLOCK)
WHERE	EV.DeadlockID IN (SELECT t.DeadlockID FROM @tDeadlock t)

SELECT	'PROCESS_LIST'
SELECT	* 
FROM	dbo.EV_DEADLOCK_PROCESS_LIST PL WITH(NOLOCK)
WHERE	PL.DeadlockID IN (SELECT t.DeadlockID FROM @tDeadlock t)

SELECT	'EXECUTION_STACK'
SELECT	* 
FROM	dbo.EV_DEADLOCK_PROCESS_LIST_EXECUTION_STACK ES WITH(NOLOCK)
WHERE	ES.DeadlockID IN (SELECT t.DeadlockID FROM @tDeadlock t)

SELECT	'RESOURCE_LIST'
SELECT	RL.*
FROM	dbo.EV_DEADLOCK_RESOURCE_LIST RL WITH(NOLOCK)
WHERE	RL.DeadlockID IN (SELECT t.DeadlockID FROM @tDeadlock t)

SELECT	'RESOURCE_OWNER_LIST'
SELECT	OL.*
FROM	dbo.EV_DEADLOCK_RESOURCE_OWNER_LIST OL WITH(NOLOCK)
WHERE	OL.DeadlockID IN (SELECT t.DeadlockID FROM @tDeadlock t)

SELECT	'WAITER_LIST'
SELECT	WL.*
FROM	dbo.EV_DEADLOCK_RESOURCE_WAITER_LIST WL WITH(NOLOCK)
WHERE	WL.DeadlockID IN (SELECT t.DeadlockID FROM @tDeadlock t)